version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 10
    reviewers:
      - "gek0z"
    assignees:
      - "gek0z"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major:
        update-types:
          - "major"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "gek0z"
    assignees:
      - "gek0z"
    groups:
      all-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci"
