/**
 * Maps city names, nicknames, and full names to NBA team codes.
 * Used by the search filter to resolve human-readable queries to 3-letter codes.
 */

const TEAM_ALIASES: Record<string, string[]> = {
  // Eastern Conference
  atlanta: ["ATL"],
  hawks: ["ATL"],
  "atlanta hawks": ["ATL"],
  brooklyn: ["BKN"],
  nets: ["BKN"],
  "brooklyn nets": ["BKN"],
  boston: ["BOS"],
  celtics: ["BOS"],
  "boston celtics": ["BOS"],
  charlotte: ["CHA"],
  hornets: ["CHA"],
  "charlotte hornets": ["CHA"],
  chicago: ["CHI"],
  bulls: ["CHI"],
  "chicago bulls": ["CHI"],
  cleveland: ["CLE"],
  cavaliers: ["CLE"],
  "cleveland cavaliers": ["CLE"],
  cavs: ["CLE"],
  detroit: ["DET"],
  pistons: ["DET"],
  "detroit pistons": ["DET"],
  indiana: ["IND"],
  pacers: ["IND"],
  "indiana pacers": ["IND"],
  miami: ["MIA"],
  heat: ["MIA"],
  "miami heat": ["MIA"],
  milwaukee: ["MIL"],
  bucks: ["MIL"],
  "milwaukee bucks": ["MIL"],
  "new york": ["NYK"],
  knicks: ["NYK"],
  "new york knicks": ["NYK"],
  knickerbockers: ["NYK"],
  orlando: ["ORL"],
  magic: ["ORL"],
  "orlando magic": ["ORL"],
  philadelphia: ["PHI"],
  "76ers": ["PHI"],
  sixers: ["PHI"],
  "philadelphia 76ers": ["PHI"],
  philly: ["PHI"],
  toronto: ["TOR"],
  raptors: ["TOR"],
  "toronto raptors": ["TOR"],
  raps: ["TOR"],
  washington: ["WAS"],
  wizards: ["WAS"],
  "washington wizards": ["WAS"],

  // Western Conference
  dallas: ["DAL"],
  mavericks: ["DAL"],
  "dallas mavericks": ["DAL"],
  mavs: ["DAL"],
  denver: ["DEN"],
  nuggets: ["DEN"],
  "denver nuggets": ["DEN"],
  "golden state": ["GSW"],
  warriors: ["GSW"],
  "golden state warriors": ["GSW"],
  dubs: ["GSW"],
  houston: ["HOU"],
  rockets: ["HOU"],
  "houston rockets": ["HOU"],
  la: ["LAL", "LAC"],
  "los angeles": ["LAL", "LAC"],
  clippers: ["LAC"],
  "la clippers": ["LAC"],
  "los angeles clippers": ["LAC"],
  clips: ["LAC"],
  lakers: ["LAL"],
  "la lakers": ["LAL"],
  "los angeles lakers": ["LAL"],
  memphis: ["MEM"],
  grizzlies: ["MEM"],
  "memphis grizzlies": ["MEM"],
  grizz: ["MEM"],
  minnesota: ["MIN"],
  timberwolves: ["MIN"],
  "minnesota timberwolves": ["MIN"],
  wolves: ["MIN"],
  "new orleans": ["NOP"],
  pelicans: ["NOP"],
  "new orleans pelicans": ["NOP"],
  pels: ["NOP"],
  "oklahoma city": ["OKC"],
  thunder: ["OKC"],
  "oklahoma city thunder": ["OKC"],
  okc: ["OKC"],
  phoenix: ["PHX"],
  suns: ["PHX"],
  "phoenix suns": ["PHX"],
  portland: ["POR"],
  "trail blazers": ["POR"],
  "portland trail blazers": ["POR"],
  blazers: ["POR"],
  sacramento: ["SAC"],
  kings: ["SAC"],
  "sacramento kings": ["SAC"],
  "san antonio": ["SAS"],
  spurs: ["SAS"],
  "san antonio spurs": ["SAS"],
  utah: ["UTA"],
  jazz: ["UTA"],
  "utah jazz": ["UTA"],

  // Legacy / Historic
  "new jersey": ["NJ"],
  nj: ["NJ"],
  "new jersey nets": ["NJ"],
  seattle: ["SEA"],
  supersonics: ["SEA"],
  "seattle supersonics": ["SEA"],
  sonics: ["SEA"],
};

export function resolveTeamQuery(query: string): string[] | null {
  const normalised = query.trim().toLowerCase();
  if (!normalised) return null;
  return TEAM_ALIASES[normalised] ?? null;
}
