#!/usr/bin/env node
// Dump the production Turso database to a SQL file that contributors can use
// to seed a local SQLite copy of the app's data. Auth and order tables are
// skipped — they hold personal data and aren't needed to run the app.

import { createClient } from "@libsql/client";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = `${ROOT}/database-backups/seed.sql`;

const SKIP_TABLES = new Set([
  "user",
  "account",
  "session",
  "verificationToken",
  "tshirt_order",
  // sqlite internals
  "sqlite_sequence",
]);

const url = process.env.TURSO_DATABASE_URL;
const authToken = process.env.TURSO_AUTH_TOKEN;
if (!url) {
  console.error("TURSO_DATABASE_URL is not set. Source your .env first.");
  process.exit(1);
}

const client = createClient({ url, authToken });

function quote(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number")
    return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "bigint") return value.toString();
  if (typeof value === "boolean") return value ? "1" : "0";
  if (value instanceof Uint8Array) {
    let hex = "";
    for (const byte of value) hex += byte.toString(16).padStart(2, "0");
    return `X'${hex}'`;
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

async function main() {
  const schema = await client.execute(
    "SELECT name, sql, type FROM sqlite_schema WHERE type IN ('table','index') AND sql IS NOT NULL ORDER BY type DESC, name",
  );

  const lines = [
    "-- WedgieTracker seed data",
    "-- Generated by `pnpm db:dump`. Do not edit by hand.",
    "PRAGMA foreign_keys=OFF;",
    "BEGIN TRANSACTION;",
    "",
  ];

  const tablesToDump = [];

  for (const row of schema.rows) {
    const name = String(row.name);
    const type = String(row.type);
    if (
      SKIP_TABLES.has(name) ||
      name.startsWith("sqlite_") ||
      name.startsWith("_litestream")
    )
      continue;

    lines.push(`DROP ${type.toUpperCase()} IF EXISTS "${name}";`);
    lines.push(`${row.sql};`);
    if (type === "table") tablesToDump.push(name);
  }

  lines.push("");

  for (const table of tablesToDump) {
    const data = await client.execute(`SELECT * FROM "${table}"`);
    if (data.rows.length === 0) continue;
    const cols = data.columns.map((c) => `"${c}"`).join(", ");
    lines.push(`-- ${table}: ${data.rows.length} rows`);
    for (const row of data.rows) {
      const values = data.columns.map((c) => quote(row[c])).join(", ");
      lines.push(`INSERT INTO "${table}" (${cols}) VALUES (${values});`);
    }
    lines.push("");
  }

  lines.push("COMMIT;");
  lines.push("PRAGMA foreign_keys=ON;");
  lines.push("");

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, lines.join("\n"));
  console.log(`Wrote ${OUT} (${tablesToDump.length} tables)`);
}

await main();
client.close();
