name: Sync Private Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to private repository
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          echo "Setting up private remote..."
          git remote add private "https://x-access-token:${GITHUB_TOKEN}@github.com/gek0z/wedgietracker.git"
          echo "Attempting to push to private repository..."
          git push private main:main --force || {
            echo "Push failed. Checking if remote is accessible..."
            git ls-remote --exit-code private
          }
