name: Sync Private Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "gek0z"
          git config --global user.email "riccardoaltieri@me.com"

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to private repository
        run: |
          # Create a temporary branch without the excluded files
          git checkout -b temp-sync
          if [ -f .github/sync-exclude.txt ]; then
            while IFS= read -r pattern; do
              git rm -r --cached "$pattern" || true
            done < .github/sync-exclude.txt
          fi
          git commit -m "Sync commit (excluding workflow files)" || true

          # Push to private repository
          git remote add private git@github.com:gek0z/wedgietracker.git
          git push private temp-sync:main --force

          # Cleanup - modified to forcefully remove untracked files
          git reset --hard HEAD
          git clean -fd  # Force remove untracked files and directories
          git checkout main
          git branch -D temp-sync
